#!/usr/bin/env ruby
require "rubygems" # ruby1.9 doesn't "require" it though
require "thor"

class Build < Thor
  desc "plan DIR", "run terraform plan on defined directory"
  def plan(dir)
    puts "Run terraform on #{Dir.pwd} | #{dir}"
  end

  desc "setup", "some setup"
  def setup
    puts "All setup"
  end

  desc "install", "some install"
  def install
    puts "All install"
  end

  desc "clean", "some clean"
  def clean
    puts "All clean"
  end

end

Build.start
