#!/usr/bin/env bash

## Jetstream
export OS_IDENTITY_API_VERSION=3
export OS_AUTH_URL=<>
export OS_AUTH_TYPE=<>
# export OS_REGION_NAME="<>" # this adds region to all assets
export OS_INTERFACE=<>

export AWS_DEFAULT_REGION="<>"
export AWS_ACCESS_KEY_ID="<>"
export AWS_SECRET_ACCESS_KEY="<>"

export TF_VAR_dme_apikey="<>"
export TF_VAR_dme_secretkey="<>"

source ./conf/openrc-personal
